-- sequence-ek
CREATE SEQUENCE PersonSeq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AddressSeq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ContactInfoSeq START WITH 1 INCREMENT BY 1;

-- Person tábla
CREATE TABLE Person (
    Id BIGINT DEFAULT NEXT VALUE FOR PersonSeq PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Address tábla
CREATE TABLE Address (
    Id BIGINT DEFAULT NEXT VALUE FOR AddressSeq PRIMARY KEY,
    PersonId BIGINT NOT NULL,
    Type VARCHAR(10) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    City VARCHAR(100) NOT NULL,
    Zip INT NOT NULL,
    Street VARCHAR(200) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Address_Person FOREIGN KEY (PersonId) REFERENCES Person(Id),
    CONSTRAINT CHK_Address_Type CHECK (Type IN ('PERMANENT', 'TEMPORARY')),
    CONSTRAINT UQ_PersonId_Type UNIQUE (PersonId, Type)
);

-- ContactInfo tábla
CREATE TABLE ContactInfo (
    Id BIGINT DEFAULT NEXT VALUE FOR ContactInfoSeq PRIMARY KEY,
    PersonId BIGINT NOT NULL,
    Type VARCHAR(10) NOT NULL,
    ContactValue VARCHAR(254) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ContactInfo_Person FOREIGN KEY (PersonId) REFERENCES Person(Id),
    CONSTRAINT CHK_ContactInfo_Type CHECK (Type IN ('EMAIL', 'PHONE', 'LINKEDIN'))
);
