CREATE SEQUENCE PersonSeq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AddressSeq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ContactInfoSeq START WITH 1 INCREMENT BY 1;

CREATE TABLE Person (
	Id BIGINT PRIMARY KEY DEFAULT NEXT VALUE FOR PersonSeq,
	FirstName  NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE Address (
    Id BIGINT PRIMARY KEY DEFAULT NEXT VALUE FOR AddressSeq,
    PersonId BIGINT NOT NULL,
    Type NVARCHAR(10) NOT NULL,
    Country NVARCHAR(100) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Zip NVARCHAR(10) NOT NULL,
    Street NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_Address_Person FOREIGN KEY (PersonId) REFERENCES Person(Id),
    CONSTRAINT CHK_Address_Type CHECK (Type IN ('PERMANENT', 'TEMPORARY')),
    CONSTRAINT UQ_PersonId_Type UNIQUE (PersonId, Type)
);

CREATE TABLE ContactInfo (
	Id BIGINT Primary KEY DEFAULT NEXT VALUE FOR ContactInfoSeq,
	PersonId BIGINT NOT NULL,
	Type NVARCHAR(10) NOT NULL,
	ContactValue NVARCHAR(254) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

	CONSTRAINT FK_ContactInfo_Person FOREIGN KEY (PersonId) REFERENCES Person(Id),
	CONSTRAINT CHK_ContactInfo_Type CHECK (Type IN ('EMAIL', 'PHONE', 'LINKEDIN'))
);